#!/bin/bash

# Construir CSR per al certificat de l'AC Arrel
openssl req -new -config acA.conf -out ac/acA.csr -keyout ac/acA/private/acA.key

if [ $? -eq 0 ]; then
   # Crear certificat autosignat de l'AC Arrel
   openssl ca -selfsign -config acA.conf -in ac/acA.csr -out ac/acA.crt -extensions acA_ext
   
   if [ $? -eq 0 ]; then
      echo "ac_crear_aCA finalitzat. Podeu procedir a crear el certificat AC Intermèdia amb 'ac_crear_acI'"
   fi
else
   echo "Error! No ha estat possible crear el certificat de l'AC Arrel."
fi
