#!/bin/bash

# Verificar si s'ha proporcionat un argument
if [ "$#" -eq 0 ]; then
    echo "Sintaxi: $0 [ acA | acI ]."
    exit 1
fi

# Assignar l'argument a una variable
ac="$1"
 
case $ac in
   "acA") index="ac/acA/db/acA.db";;
	"acI") index="ac/acI/db/acI.db";;
	    *) echo "Error! No existeix l\'AC $1. Heu d'especificar quina AC voleu llistar: ac_llistar_certs [acA | acA]."; exit 1;;
esac

# Comprova que el fitxer índex realmente existeixi
if [ ! -f "$index" ]; then
  echo "Error! El fitxer índex de l'AC $index no existeix. Comprovau que heu generat els certificats de les AC Arrel i AC Intermèdia."
  exit 1
fi

# Mostra capçalera
echo "Certificats a $index"
echo

# Usa awk per a mostrar les dades de cada certificat
awk -F"\t" '{
  estat=($1=="V") ? "VALID" : "REVOCAT";
  expira=substr($2,5,2)"/"substr($2,3,2)"/"substr($2,1,2)" "substr($2,7,2)":"substr($2,9,2)":"substr($2,11,2);
  
  if ($3 == "") {
    revocacio="No revocat!";
  } else {
    revocacio=substr($3,5,2)"/"substr($3,3,2)"/"substr($3,1,2) " "substr($3,7,2)":"substr($3,9,2)":"substr($3,11,2) " (" substr($3,15) ")";
  }

  print "Número de sèrie.....", $4;
  print "DN..................", $6;
  print "Expira..............", expira;
  print "Estat...............", estat;
  print "Revocació i motiu...", revocacio;

  print ""
}' "$index"

echo ""

