#!/bin/bash

# Llegim paràmetre: Fitxer amb el CSR per a mostrar
fitxer="$1"

if [ -z $fitxer ]; then
   echo "Error de sintaxi. Usau ./ca_mostrar_csr <fitxer>, on el nom del fitxer no pot quedar en blanc."
else
   # Els fitxers CSR s'emmagatzemen a la carpeta ./certs amb extensió .csr
   fitxer="./certs/$fitxer.csr"
   if [ -f "$fitxer" ]; then
      openssl req -in "$fitxer" -noout -text
   else
      echo "Error! No s'ha trobat el fitxer CSR $fitxer."
   fi
fi

